### ISSUE TITLE
Kodi crashes on exit (BlockingIOError)

### ISSUE THREAD

**Issue by Maven85** [anxdpanic/script.common.plugin.cache#19]
Hi @anxdpanic,

Kodi crashes on exit with the latest Nightlies because this addon produces a 'BlockingIOError'.

[kodi.log](https://github.com/anxdpanic/script.common.plugin.cache/files/3925933/kodi.log)

**Comment by anxdpanic** [comment]
It should be handled cleanly now in #20. I've attached a zip with the changes if you could give that a try.
[script.common.plugin.cache-2.6.1~alpha1.zip](https://github.com/anxdpanic/script.common.plugin.cache/files/3928050/script.common.plugin.cache-2.6.1.alpha1.zip)

**Comment by anxdpanic** [comment]
btw I have heavily updated a fork of plexbmc that's ready for Kodi 19. 
I have added and removed stuff so it might not meet your needs, but might be worth a look.
https://github.com/anxdpanic/plugin.video.composite_for_plex#composite

**Comment by Maven85** [comment]
> It should be handled cleanly now in #20. I've attached a zip with the changes if you could give that a try.
> [script.common.plugin.cache-2.6.1~alpha1.zip](https://github.com/anxdpanic/script.common.plugin.cache/files/3928050/script.common.plugin.cache-2.6.1.alpha1.zip)

Kodi still can not be finished cleanly
[kodi.log](https://github.com/anxdpanic/script.common.plugin.cache/files/3930905/kodi.log)

**Comment by Maven85** [comment]
> btw I have heavily updated a fork of plexbmc that's ready for Kodi 19.
> I have added and removed stuff so it might not meet your needs, but might be worth a look.
> https://github.com/anxdpanic/plugin.video.composite_for_plex#composite

Looks very good. I tested it briefly and worked well.
If you want, I would create PRs if I noticed something. I could also help with the translation into German.

**Comment by anxdpanic** [comment]
> Kodi still can not be finished cleanly
> [kodi.log](https://github.com/anxdpanic/script.common.plugin.cache/files/3930905/kodi.log)

Thanks for testing. When time allows, I will try to stage a portable installation to see if I can reproduce the issue and hopefully get to the bottom of it.

**Comment by anxdpanic** [comment]
> Looks very good. I tested it briefly and worked well.
> If you want, I would create PRs if I noticed something. I could also help with the translation into German.

PR's and translation are definitely welcome and very much appreciated 👍

**Comment by Maven85** [comment]
> > Kodi still can not be finished cleanly
> > [kodi.log](https://github.com/anxdpanic/script.common.plugin.cache/files/3930905/kodi.log)
> 
> Thanks for testing. When time allows, I will try to stage a portable installation to see if I can reproduce the issue and hopefully get to the bottom of it.

Maybe it's only a problem on Windows. On Android I have no issues.

**Comment by MilhouseVH** [comment]
It's an issue on Linux, too - from latest LibreELEC (with latest #20 applied - Kodi no longer crashes but the exit is not clean or timely as Kodi has to kill the script):

```
2019-12-09 22:29:55.583 T:1225  NOTICE: CWebServer[8080]: Stopped
2019-12-09 22:29:55.584 T:1225  NOTICE: stop dvd detect media
2019-12-09 22:30:00.867 T:1225   ERROR: CPythonInvoker(1, /storage/.kodi/addons/script.common.plugin.cache/resources/lib/entry_point.py): script didn't stop in 5 seconds - let's kill it
2019-12-09 22:30:00.895 T:1255   ERROR: Traceback (most recent call last):
2019-12-09 22:30:00.895 T:1255   ERROR:   File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 238, in run
2019-12-09 22:30:00.899 T:1255   ERROR: (self.clientsocket, address) = sock.accept()
2019-12-09 22:30:00.900 T:1255   ERROR:   File "/usr/lib/python3.7/socket.py", line 212, in accept
2019-12-09 22:30:00.901 T:1255   ERROR: BlockingIOError
2019-12-09 22:30:00.901 T:1255   ERROR: :
2019-12-09 22:30:00.901 T:1255   ERROR: [Errno 11] Resource temporarily unavailable
2019-12-09 22:30:00.901 T:1255   ERROR: 
                                            During handling of the above exception, another exception occurred:
2019-12-09 22:30:00.901 T:1255   ERROR: Traceback (most recent call last):
2019-12-09 22:30:00.902 T:1255   ERROR:   File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/entry_point.py", line 16, in <module>
2019-12-09 22:30:00.904 T:1255   ERROR: service.run()
2019-12-09 22:30:00.904 T:1255   ERROR:   File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/service.py", line 38, in run
2019-12-09 22:30:00.906 T:1255   ERROR: s.run()
2019-12-09 22:30:00.906 T:1255   ERROR:   File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 250, in run
2019-12-09 22:30:00.909 T:1255   ERROR: time.sleep(0.5)
2019-12-09 22:30:00.909 T:1255   ERROR: SystemExit
```
http://ix.io/240O

**Comment by anxdpanic** [comment]
Was finally able to reproduce, hopefully get the issue resolved tonight.

**Comment by anxdpanic** [comment]
Was a little more involved than expected but should be fixed now, in all my shutdowns it terminated between 200 and 500ms now.

@Maven85 and @MilhouseVH an alpha zip is attached.

[script.common.plugin.cache-2.6.1~alpha2.zip](https://github.com/anxdpanic/script.common.plugin.cache/files/3942469/script.common.plugin.cache-2.6.1.alpha2.zip)

**Comment by MilhouseVH** [comment]
@anxdpanic thanks, #20 is now working well and script.common.plugin.cache exists cleanly and without the 5 second delay.

I'm still seeing a crash on Kodi exit but I don't think this is script.common.plugin.cache related (this is the crash log: http://ix.io/241q, even though script.common.plugin.cache is disabled). In the system log at the end we can see that `kodi.sh` is failing with a mixture of Python3 and memory allocation errors.

**Comment by Maven85** [comment]
I can confirm that it works on Windows. Thanks!

**Comment by anxdpanic** [comment]
Thanks for confirming, I'll get it submitted to the official repository

@MilhouseVH I don't have any knowledge of C or the C <-> Python interface so I can't be much help with the `kodi.sh` issue

**Comment by MilhouseVH** [comment]
>  so I can't be much help with the kodi.sh issue

Yeah no worries it was just for general info at this time, as I don't think it's related to any specific add-on!
